Description: >
    Udacity Cloud DevOps Engineer - Project 3 - IAM Role

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

######################################
####### IAM - Role             #######
######################################

  S3AccessIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

  S3AccessIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AccessIAMPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject*
            Resource: "*"
      Roles:
      - Ref: S3AccessIAMRole

  S3AccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: S3AccessIAMRole